TRNS-0004 Cache
berhram/Words504 pull request #106
Opened 2023-04-19 16:06 UTC by eels911

2023-04-20 12:32 UTC, JohnnySC requested changes

2023-04-20 12:32 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/translate/data/cache/entities/TranslateCache.kt
> +data class TranslateCache(
TranslationCache

2023-04-21 04:56 UTC, JohnnySC requested changes

2023-04-21 04:56 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/translate/data/cache/entities/TranslateCache.kt
> +data class TranslationCache(
надо переименовать сам файл

2023-04-21 09:30 UTC, JohnnySC approved these changes

2023-04-21 09:31 UTC, JohnnySC requested changes

2023-04-21 09:31 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/translate/data/cache/entities/TranslationCache.kt
> +    private val id: String,
стоп: приватные поля же не будут работать с рум классом

2023-04-21 09:55 UTC, JohnnySC approved these changes

2023-04-21 09:58 UTC, TroyanRoman approved these changes

2023-04-21 09:59 UTC, merged