DICT-0008 choose language vm
berhram/Words504 pull request #108
Opened 2023-04-20 17:14 UTC by ekzakh

Вью модель для экрана выбора языка.

2023-04-21 03:49 UTC, JohnnySC requested changes

2023-04-21 03:49 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/presentation/ChooseLanguageViewModelTest.kt
> +        viewModel.save()
здесь надо проверить что в репу пошел сейв

2023-04-21 03:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/data/repository/ChooseLanguageRepository.kt
> +    fun userChoice(languageCache: LanguageCache)
если сейвим пишем fun saveUserChoice(language) а если получаем то без глагола fun userChoice() : Language

2023-04-21 03:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/data/repository/ChooseLanguageRepository.kt
> +        override fun save() = chosenLanguage.save(userChoice.read())
здесь нарушаем ДРАЙ : можно вызвать функцию которая уже есть chosenLanguage.save(fetchUserChoice())

2023-04-21 03:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageState.kt
> +    data class Initial(private val languages: List<LanguageUi>) : ChooseLanguageState
DRY попробуй сделать абстракт класс абстракт с листом там

2023-04-21 03:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageViewModel.kt
> +            languagesCache.addAll(repository.languages())
на обычном повороте же сюда будет добавлено еще столько же

2023-04-21 03:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageViewModel.kt
> +        private fun makeChosen(language: LanguageCache): List<LanguageUi> =
приватная функция говорит о том что что т пошло не так : подумай как убрать. Возможно тебе нужен простой мапер который сам все сделает под капотом

2023-04-21 03:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/LanguageUi.kt
> +    data class NotChosen(private val id: String, private val value: String) : LanguageUi
нарушаем драй: сделай абстракт класс абстракт с этими полями

2023-04-21 03:49 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/presentation/ChooseLanguageViewModelTest.kt
> + * @author Asatryan on 17.04.2023
мою фамилию можно и убрать из джавадока

2023-04-22 23:25 UTC, JohnnySC requested changes

2023-04-22 23:25 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/sl/ChooseLanguageModule.kt
> +
Пустоты убери

2023-04-23 04:14 UTC, JohnnySC requested changes

2023-04-23 04:14 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageViewModel.kt
> +            val userChoice = repository.userChoice()
возможно зазря берешь юзерчойс : перемести внутрь ифа

2023-04-23 04:18 UTC, JohnnySC approved these changes

2023-04-23 04:35 UTC, berhram approved these changes

2023-04-23 04:35 UTC, merged