Feature/init 0002
berhram/Words504 pull request #117
Opened 2023-04-27 07:47 UTC by blastka

Надеюсь что я верно поняла задумку с InitialResult

2023-04-27 10:49 UTC, JohnnySC requested changes

2023-04-27 10:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/domain/InitialResult.kt
> +            communication.map(InitialUiState.Loading)
а зачем прогрес если уходим с экрана?

2023-04-27 10:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/domain/InitialResult.kt
> +            communication.map(InitialUiState.Loading)
зачем загрузку если уходим с экрана

2023-04-27 10:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/domain/InitialResult.kt
> +            communication.map(InitialUiState.Loading)
зачем загрузка если ошибку показываем?

2023-04-27 10:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/presentation/InitialCommunication.kt
> +interface InitialCommunication {
комуникация которая не наследует комуникацию. посмотри в проекте другие и удали функцию из нее

2023-04-27 10:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/presentation/InitialViewModel.kt
> +interface InitialInit {
сделай интерфейс сегрегацию здесь

2023-04-27 10:49 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/initial/presentation/InitialViewModelTest.kt
> +    fun map(source: InitialResult)
fun changeExpected(expected: InitialResult)

2023-04-27 10:53 UTC, JohnnySC requested changes

2023-04-27 10:53 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/presentation/InitialViewModel.kt
> +        handle({ interactor.init() }) { initialResult ->
перед хендлом надо прогресс показать

2023-04-28 04:21 UTC, JohnnySC approved these changes

2023-04-28 04:23 UTC, berhram approved these changes

2023-04-28 04:23 UTC, merged