DICT-0011 words dao
berhram/Words504 pull request #118
Opened 2023-04-27 13:20 UTC by ekzakh

Дао для получения слов в предложения и переводов слов в предложении

2023-04-29 08:53 UTC, JohnnySC requested changes

2023-04-29 08:53 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/AppDataBase.kt
> +        abstract fun wordsDao(): WordsDao
просто положи функцию в интерфейс

2023-04-30 08:13 UTC, ekzakh commented on app/src/main/java/ru/easycode/words504/AppDataBase.kt
> +        abstract fun wordsDao(): WordsDao
тут так нельзя, если положу в интерфейс, то в классе нужно переопределить, а руму требуется абстрактная функция, он сам ее будет переопределять

2023-04-30 08:25 UTC, JohnnySC requested changes

2023-04-30 08:25 UTC, JohnnySC commented on app/src/androidTest/java/ru/easycode/words504/WordsDaoTest.kt
> +        private data class FakeCombo(
да. надо сделать приватными поля в конструктор

2023-04-30 08:25 UTC, JohnnySC commented on app/src/androidTest/java/ru/easycode/words504/WordsDaoTest.kt
> +interface WordsDaoTest {
интерфейс уже не нужен. сразу класс

2023-04-30 08:25 UTC, JohnnySC commented on app/src/androidTest/java/ru/easycode/words504/WordsDaoTest.kt
> +        fun test_scenario() {
сценарий у нас : данные по слову по его дикшнари форме

2023-04-30 08:25 UTC, JohnnySC commented on app/src/androidTest/java/ru/easycode/words504/WordsDaoTest.kt
> +        private interface FakeCombo {
если нет методов то и интерфейс не нужен. сразу класс

2023-04-30 08:25 UTC, JohnnySC commented on app/src/androidTest/java/ru/easycode/words504/WordsDaoTest.kt
> +        private interface FakeWordCombo {
то же самое здесь: мы не пишем интерфейс если методов нет

2023-04-30 08:25 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/AppDataBase.kt
> +        abstract fun wordsDao(): WordsDao
в абстрактном классе не надо определять метод

2023-04-30 08:54 UTC, JohnnySC requested changes

2023-04-30 08:54 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/AppDataBase.kt
>  interface AppDataBase {
на самом деле нейминг немного не тот: это же не все что есть: а конкретно дикшнари. и да . перемести в пакет дикшнари

2023-04-30 14:54 UTC, JohnnySC approved these changes

2023-05-01 12:37 UTC, berhram approved these changes

2023-05-01 14:17 UTC, merged