Feature/admt 0009 sentence fragment
berhram/Words504 pull request #119
Opened 2023-04-29 08:39 UTC by 00hadron

AdminFragment для создания предложения:
- тулбар с кнопкой назад
- SentenceInputLayout
- WordsLinearLayout из задачи ADMT-0012
- AdminViewModel из задачи AMDT-0008
- add,  save кнопки

2023-04-29 08:49 UTC, JohnnySC requested changes

2023-04-29 08:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminActivity.kt
> +        supportFragmentManager.beginTransaction()
1. if (saved intance state == null)
2. у нас есть интерфейс Screen и абстракт класс Replace : отнаследуйся и юзай

2023-04-29 08:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminFragment.kt
> +        binding.adminFragmentToolbar.setOnClickListener { }
что за пустой кликлиснер?

2023-04-29 08:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminFragment.kt
> +        binding.adminFragmentToolbar.setOnClickListener { }
надо вернуться назад по стеку. у вмки должен быть метод

2023-04-29 08:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminFragment.kt
> +        binding.adminAddButton.setOnClickListener { binding.wordsLinearLayout.add() }
а где клик на сейв кнопку?

2023-04-29 08:50 UTC, JohnnySC requested changes

2023-04-29 08:50 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminFragment.kt
> +class AdminFragment : BaseFragment<AdminViewModel>() {
давай назовем по сути : например AdminSentenceFragment и также переименуем вмку AdminSentenceViewModel

2023-04-30 13:04 UTC, JohnnySC requested changes

2023-04-30 13:04 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminActivity.kt
> +class AdminActivity : BaseActivity<AdminSentenceViewModel>() {
ну админ активити должно быть админактивитивьюмодель

2023-04-30 15:16 UTC, JohnnySC approved these changes

2023-05-01 10:33 UTC, JohnnySC requested changes

2023-05-01 10:33 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminSentenceViewModel.kt
> +interface AdminSentenceViewModel {
юзать существующую вмку

2023-05-02 14:39 UTC, berhram approved these changes

2023-05-02 14:40 UTC, merged