CORE-0020 navigation
berhram/Words504 pull request #12
Opened 2023-03-15 13:08 UTC by Nilsolk

2023-03-15 13:22 UTC, JohnnySC requested changes

2023-03-15 13:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/Screen.kt
> +    abstract class Base(private val containerId: Int, private val fragment: Fragment) : Screen {
передаем не сам фрагмент, а его класс чтобы создавать сам фрагмент именно в момент реплейса

2023-03-15 13:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/Screen.kt
> +    abstract class Base(private val containerId: Int, private val fragment: Fragment) : Screen {
убери контейнер  и забей R.id.container

2023-03-15 20:16 UTC, berhram requested changes

2023-03-15 20:16 UTC, berhram commented on core/src/main/java/ru/easycode/words504/core/Screen.kt
> +    abstract class Base(private val clazz: Class<Fragment>) : Screen {
класс Base абстракт??

2023-03-16 03:18 UTC, JohnnySC requested changes

2023-03-16 03:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/Screen.kt
> +    abstract class Base(private val clazz: Class<Fragment>) : Screen {
ну пускай будет. все равно у него будет много наследников

2023-03-16 03:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/Screen.kt
> +        protected abstract val resId: Int
сделай по дефолту значение R.id.container и перемести в конструктор вторым аргументом

2023-03-16 07:17 UTC, berhram approved these changes

2023-03-16 09:55 UTC, JohnnySC requested changes

2023-03-16 09:55 UTC, JohnnySC commented on core/src/main/res/values/ids.xml
> +<?xml version="1.0" encoding="utf-8"?>
а это проблема. лучше в мейн активити добавь некий фрейм лейаут с этим айди

2023-03-16 10:04 UTC, JohnnySC requested changes

2023-03-16 13:30 UTC, JohnnySC approved these changes

2023-03-16 13:30 UTC, merged