CORE-0029 fragment view binding
berhram/Words504 pull request #120
Opened 2023-04-29 11:17 UTC by ekzakh

Вью биндинг в базовом фрагменте

2023-04-29 14:33 UTC, JohnnySC requested changes

2023-04-29 14:33 UTC, JohnnySC commented on app/build.gradle
> +    buildFeatures {
duplicate

2023-04-29 14:33 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/presentation/BaseFragment.kt
> +    abstract fun fragmentBinding(inflater: LayoutInflater, container: ViewGroup?): V
protected abstract fun

2023-04-30 04:17 UTC, JohnnySC approved these changes

2023-04-30 14:08 UTC, berhram approved these changes

2023-04-30 14:08 UTC, merged