feat/INIT-0003_initial_repository
berhram/Words504 pull request #123
Opened 2023-05-02 11:21 UTC by berhram

2023-05-02 12:32 UTC, JohnnySC requested changes

2023-05-02 12:32 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/data/BaseInitialRepository.kt
> +        val allLanguages = languagesCloud.languages().map { it.map(languageMapper) }
не надо лезть в сеть если в кеше уже есть

2023-05-03 02:35 UTC, JohnnySC approved these changes

2023-05-03 04:19 UTC, ekzakh approved these changes

2023-05-03 04:20 UTC, merged