INIT-0001 InitialFragment
berhram/Words504 pull request #125
Opened 2023-05-02 19:08 UTC by ekzakh

InitialFragment 
InitialModule для создания вьюмодели нужно доделать, когда будет готов репозиторий и все необходимое для него. 
![InitialFragment](https://user-images.githubusercontent.com/122279213/235762167-404de3e3-2006-4982-b0be-5732b6ed72a4.png)

2023-05-03 02:31 UTC, JohnnySC requested changes

2023-05-03 02:31 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/presentation/InitialScreen.kt
> +object InitialScreen : Screen.Add(InitialFragment::class.java)
почему ад если надо реплейс?

2023-05-03 02:47 UTC, JohnnySC requested changes

2023-05-03 02:47 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/presentation/InitialFragment.kt
> +                when (state) {
фатальная ошибка: если ты в фрагменте пишешь проверку на инстанс то значит твое ООП хромает

2023-05-03 02:47 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/initial/presentation/InitialUiState.kt
> +    interface ApplyError {
не нужно никаких интерфейс сегрегейшнов : просто напиши 2 метода в сам юай стейт и кто знает как тот определит его

2023-05-04 08:54 UTC, JohnnySC approved these changes

2023-05-04 08:55 UTC, berhram approved these changes

2023-05-04 08:55 UTC, merged