Dsgn-0002 Custom progress view
berhram/Words504 pull request #126
Opened 2023-05-02 22:34 UTC by TroyanRoman

2023-05-03 02:43 UTC, JohnnySC requested changes

2023-05-03 02:43 UTC, JohnnySC commented on app/src/main/res/layout/progress_view.xml
> +        <ImageView
а нельзя было поставить фоном текствю?

2023-05-03 02:43 UTC, JohnnySC commented on app/src/main/res/layout/progress_view.xml
> +            android:textDirection="ltr"
зачем направление текста если он состоит из 1 буквы?

2023-05-03 02:43 UTC, JohnnySC commented on app/src/main/res/values/strings.xml
> +    <string name="progress_start_symbol">カ</string>
а это прям нужно? нельзя из кода брать?

2023-05-03 02:43 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/views/ProgressView.kt
> +    private var translations: ProgressAnimator = ProgressAnimator.Empty()
в ините же ставится значение. значит вар не нужно. можно объявить вал и в ините проставить значение сразу

2023-05-03 02:43 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/views/ProgressView.kt
> +        frameLeft = getChildAt(0) as FrameLayout
вместо завязки на порядок брал бы по айди. потому что завтра ты поменяешь структуру  хмл

2023-05-03 02:44 UTC, JohnnySC commented
А нельзя прямо в описание к ПР поставить гифку загрузки? @TroyanRoman

2023-05-09 04:40 UTC, JohnnySC requested changes

2023-05-09 04:40 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/views/ProgressView.kt
> +        textViewLeft = getChildAt(0) as TextView
лучше просто через айди чтоб не завязываться на порядок

2023-05-09 04:40 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/views/ProgressView.kt
> +            layoutParams.width = (screenWidth * 0.6).toInt()
что это за 0.6? что оно значит?

2023-05-09 04:40 UTC, JohnnySC commented on app/src/main/res/values/dimens.xml
> +    <dimen name="min_text">12dp</dimen>
быть может  все же sp ?

2023-05-09 12:32 UTC, berhram commented on app/src/main/java/ru/easycode/words504/views/ProgressView.kt
> +            layoutParams.width = (screenWidth * 0.6).toInt()
если указали слишком маленькую ширину вью, чтобы она уродливо не выглядела, она будет 60% от ширины экрана. вынес в консты

2023-05-09 14:10 UTC, berhram approved these changes

2023-05-09 14:10 UTC, merged