Feature/dict 0007 choose language fragment
berhram/Words504 pull request #129
Opened 2023-05-03 08:05 UTC by eels911

2023-05-03 08:09 UTC, JohnnySC requested changes

2023-05-03 08:09 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageFragment.kt
> +            binding.root.visibility = View.GONE
что за низкоуровневый код?

2023-05-03 08:09 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/Mapper.kt
> +interface Mapper<R, S> {
а у нас нет мапера в коре??

2023-05-06 08:28 UTC, JohnnySC requested changes
что за мракобесие с вью суффиксами....

2023-05-06 14:17 UTC, JohnnySC requested changes

2023-05-06 14:17 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageAdapter.kt
> +    fun click(item: LanguageUi)
Дженерик бы

2023-05-06 14:17 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/presentation/ChooseLanguageAdapter.kt
> +    private val view: View,
Биндинг бы

2023-05-06 14:17 UTC, JohnnySC commented on app/src/main/res/layout/language_item.xml
> +        android:textColor="#1C1B1F"
Хардкоды

2023-05-07 03:02 UTC, JohnnySC requested changes

2023-05-07 03:02 UTC, JohnnySC commented on app/src/main/res/layout/fragment_choose_language.xml
> +        tools:text="Choose you language" />
зачем тулс текст если есть уже текст и тем более с опечаткой

2023-05-07 03:02 UTC, JohnnySC commented on app/src/main/res/layout/fragment_lang.xml
> +    android:id="@+id/langRecyclerView"
сам файл переименовать бы и дать сюда лейаутманагер

2023-05-07 03:02 UTC, JohnnySC commented on app/src/main/res/values/dimens.xml
> +    <dimen name="medium">16dp</dimen>
если начал выносить сюда то и все хардкоды убери из всех файлов

2023-05-07 03:02 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/MainViewModelTest.kt
> +                assertEquals(InitialScreen, emittedScreen)
это хардкод. скрин должен прийти снаружи и метод не должен быть завязан на константу

2023-05-07 10:53 UTC, JohnnySC approved these changes

2023-05-07 15:06 UTC, berhram approved these changes

2023-05-07 15:06 UTC, merged