admt-0017 Lessons list repository
berhram/Words504 pull request #133
Opened 2023-05-28 18:50 UTC by ekzakh

2023-05-28 18:53 UTC, ekzakh commented on app/src/main/java/ru/easycode/words504/admintools/lessonslist/presentation/AdminLessonsListViewModel.kt
> +        // todo remove it later
этот метод временный чтобы заполнить данными бдху, удалю его после ревью

2023-05-29 05:51 UTC, JohnnySC requested changes

2023-05-29 05:51 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/lessonslist/data/LessonsListRepositoryBase.kt
> +    override fun chooseLesson(id: String) = simpleStorage.save(CHOSEN_LESSON_KEY, id)
а когда будет читать откуда возьмем ключ? или будем дублировать? сделай полноценный класс который отвечает за сохранение выбора и чтение его интерфейс сегрегировано и чтоб сторадж приходил в него

2023-05-29 05:51 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/lessonslist/data/cache/LessonCache.kt
> +        val jsonData: String
мне кажется джейсон дата должна генериться по запросу через метод

2023-05-29 05:51 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/sl/AdminScopeModule.kt
> +            return@lazy Room.databaseBuilder(
нам бы нормальную обертку чтоб инкапсулировать низкоуровневое от рума

2023-05-30 04:04 UTC, JohnnySC requested changes

2023-05-30 04:04 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/sl/AdminScopeModule.kt
> +        ).create(LessonConverters.Base(Serialization.Base()))
сериализация дубликат

2023-05-30 04:04 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/RoomDatabaseWrapper.kt
> +    override fun <K : Any> create(typeConverter: K): T =
а разве конвертер не должен быть хоть чьим т наследником??

2023-05-30 04:06 UTC, JohnnySC requested changes

2023-05-30 04:06 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/lessonslist/data/cache/LessonConverters.kt
> +    fun toLessonJson(lessonCloud: LessonCloud.Base): String
есть смысл сделать дженерик типизированный интерфейс и вынести в ядро и его же отдавать в метод создания рума через конвертер

2023-05-31 06:27 UTC, berhram approved these changes

2023-05-31 06:27 UTC, merged