CORE-0009 add SharedPrefWrapper
berhram/Words504 pull request #16
Opened 2023-03-15 19:30 UTC by eels911

2023-03-15 20:26 UTC, berhram requested changes

2023-03-15 20:26 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +interface SharedPrefWrapper {
где тут паттерн обёртка? что оборачивается

2023-03-15 20:26 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +    class Release: SharedPref("test", Context.MODE_APPEND)
почему такой ключ и private mode?

2023-03-16 03:21 UTC, JohnnySC requested changes

2023-03-16 03:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +     open class SharedPref(
никогда не юзай опен классы. абстрактный пиши

2023-03-16 03:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +    fun create(context: Context):SharedPreferences
должна быть функция fun sharedPreferences() : SharedPreferences
context в конструктор абстрактного класса

2023-03-16 03:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +        val visibility: Int
дай дефолтное значение Context.MODE_PRIVATE

2023-03-16 03:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +interface SharedPrefWrapper {
interface ProvideSharedPreferences переименуй

2023-03-16 03:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +    class Release: SharedPref("test", Context.MODE_APPEND)
для релиза надо релиз

2023-03-16 06:27 UTC, eels911 commented on core/src/main/java/ru/easycode/words504/data/SharedPrefWrapper.kt
> +interface SharedPrefWrapper {
интерфейс - это и есть обертка

2023-03-16 08:20 UTC, berhram approved these changes

2023-03-16 09:33 UTC, merged