ProvideViewModel interface created in ServiceLocator package
berhram/Words504 pull request #17
Opened 2023-03-15 20:16 UTC by TroyanRoman

2023-03-15 20:18 UTC, berhram commented
Добавь номер таски в коммит и ПР

2023-03-15 20:19 UTC, berhram approved these changes

2023-03-16 03:18 UTC, JohnnySC requested changes

2023-03-16 03:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/sl/ProvideViewModel.kt
> +    fun <T : ViewModel> provide(clazz: Class<T>, owner: ViewModelStoreOwner): T
функция должна называться viewModel

2023-03-16 09:53 UTC, JohnnySC approved these changes

2023-03-16 09:53 UTC, merged