CORE-0011 add JSONConvertable
berhram/Words504 pull request #19
Opened 2023-03-16 10:29 UTC by eels911

2023-03-16 11:28 UTC, JohnnySC requested changes

2023-03-16 11:28 UTC, JohnnySC commented on app/build.gradle
> +    implementation "com.google.code.gson:gson:2.10.1"
а разве гсона из ретрофита нельзя получить? попробуй убрать это и посмотри будет работать или нет

2023-03-16 11:28 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +    fun <T>toString(json:String, obj: T): T
выравнивай код когда закончила писать контрол шифт Л

2023-03-16 11:28 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +            TODO("Not yet implemented")
и где код? получи в конструктор gson: Gson и напиши код через него

2023-03-16 22:40 UTC, berhram requested changes

2023-03-16 22:40 UTC, berhram commented on core/build.gradle
> +    implementation "com.google.code.gson:gson:$rootProject.gsonVersion"
добавила сюда, тогда зачем ещё и в другой модуль? можешь эту же зависимость переиспользовать

2023-03-16 22:40 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +interface ProvideSerializationGson {
имхо лучше убрать слово GSON, это всё таки деталь имплементации. вдруг завтра будем через moshi условно говоря

2023-03-16 22:40 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +    fun toJson(str: Any): String
название аргумента str предполагает строку, а приходят то другие объекты

2023-03-16 22:40 UTC, berhram commented on core/src/test/java/ru/easycode/words504/ProvideSerializationGsonTest.kt
> +        assertEquals(actual, expected)
ты пытаешься строку сравнить с объектом и надеешься на иквелс?

2023-03-17 02:05 UTC, JohnnySC requested changes

2023-03-17 02:05 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/ProvideSerializationGsonTest.kt
> +    data class FakeSerializedObject(val id: String)
private data class

2023-03-17 04:47 UTC, JohnnySC requested changes

2023-03-17 04:47 UTC, JohnnySC commented on app/build.gradle
> +    implementation "com.google.code.gson:gson:2.10.1"
убери отсюда зависимость. оставь только в ядре

2023-03-17 04:47 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +    fun <T> fromJson(json: String, obj: Class<T>): T
clazz  а не obj

2023-03-17 04:47 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +        }
когда функция в 1 линию не пиши return а юзай равно =

2023-03-17 05:14 UTC, JohnnySC requested changes

2023-03-17 05:14 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ProvideSerializationGson.kt
> +interface ProvideSerializationGson {
interface Serialization переименуй

2023-03-17 05:51 UTC, JohnnySC requested changes

2023-03-17 05:51 UTC, JohnnySC commented on core/build.gradle
> +    implementation "com.google.code.gson:gson:$rootProject.gsonVersion"
не имплементейшн, а апи

2023-03-17 05:51 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/SerializationTest.kt
> +    fun readRightString() {
давай сразу пофиксим нейминги тестовый функций 
пустое не нужно

`test deserialize object`
`test serialize object`

2023-03-17 06:51 UTC, JohnnySC approved these changes

2023-03-17 07:15 UTC, berhram approved these changes

2023-03-17 07:16 UTC, merged