CORE-0016 add BaseViewModel
berhram/Words504 pull request #21
Opened 2023-03-16 15:05 UTC by TroyanRoman

2023-03-16 22:28 UTC, berhram approved these changes

2023-03-17 02:02 UTC, JohnnySC requested changes

2023-03-17 02:02 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/sl/BaseViewModel.kt
> +    protected fun  handle(io: suspend () -> Unit, ui: () -> Unit, coroutineScope: CoroutineScope) =
двойной пробел, отреформать через контрол шифт Л

2023-03-17 02:02 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/sl/BaseViewModel.kt
> +    protected fun  handle(io: suspend () -> Unit, ui: () -> Unit, coroutineScope: CoroutineScope) =
нет дженерика! ио лямбда должна вернуть то, что надо прокинуть на юай

2023-03-17 02:02 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/sl/BaseViewModel.kt
> +    protected fun  handle(io: suspend () -> Unit, ui: () -> Unit, coroutineScope: CoroutineScope) =
также убери корутин скоуп. мы и так находимся в вьюмодельке. у нас есть доступ к вмскоупу

2023-03-17 04:44 UTC, JohnnySC requested changes

2023-03-17 04:44 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/presentation/BaseViewModel.kt
> +    protected fun <T> handle(io: suspend () -> T, ui: (result: T) -> Unit) =
убрать нейминг с дженерика и ограничить Т ноннул

2023-03-17 07:21 UTC, JohnnySC approved these changes

2023-03-17 07:26 UTC, merged