CORE-0013 StringStorage
berhram/Words504 pull request #22
Opened 2023-03-16 17:42 UTC by Nilsolk

2023-03-16 22:24 UTC, berhram requested changes

2023-03-16 22:24 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/SimpleStorage.kt
> +    class Storage(private val provideSharedPref: ProvideSharedPreferences)
как этот класс связан с интерфейсом, куда он вложен? чего-то не хватает

2023-03-17 02:06 UTC, JohnnySC requested changes

2023-03-17 02:06 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SimpleStorage.kt
> +    class Storage(private val provideSharedPref: ProvideSharedPreferences)
надо было написать класс Бейз и наследовать симпл сторедж и прописать функии

2023-03-17 04:40 UTC, JohnnySC requested changes

2023-03-17 04:40 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SimpleStorage.kt
> +            return outputString ?: ""
зачем елвисом пустота если у нас есть дефолт?

2023-03-17 04:45 UTC, JohnnySC requested changes

2023-03-17 04:45 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SimpleStorage.kt
> +            provideSharedPref.sharedPreferences().edit().putString(key, value).apply()
лучше вынести из 2 методов провайд.шердпреф в поле класса

2023-03-17 05:02 UTC, JohnnySC requested changes

2023-03-17 05:02 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/SimpleStorage.kt
> +            return sharedPreferences.getString(key, default)!!
зачем тебе !! если есть елвис и можно вернуть дефолт. и убери ретурн

2023-03-17 07:42 UTC, JohnnySC approved these changes

2023-03-17 07:42 UTC, berhram approved these changes

2023-03-17 07:43 UTC, merged