core-0012 object storage
berhram/Words504 pull request #31
Opened 2023-03-17 16:56 UTC by ekzakh

2023-03-17 17:05 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +            val json = stringStorage.read(key, clazz.name)
добавь защиту от дурака - дефолтное значение

2023-03-17 17:27 UTC, berhram submitted a review, later dismissed

2023-03-17 17:27 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +        override fun <T> read(key: String, default: String, clazz: Class<T>): T {
под дефолтом имел ввиду дефолтное значение обьекта который хотим получить. тогда можно кстати не отдвать Class отдельно

2023-03-17 17:27 UTC, berhram commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +            return serialization.fromJson(json, clazz)
у нас будет экспешн если не существует по такому ключу ничего. сделай чтобы в таком случае отдавало дефолт

2023-03-17 17:57 UTC, ekzakh commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +        override fun <T> read(key: String, default: String, clazz: Class<T>): T {
class нужен что бы передать его в serialization.fromJson(json: String, clazz: Class<T>). Как обойтись без него?

2023-03-18 04:40 UTC, JohnnySC requested changes

2023-03-18 04:40 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +                val json = stringStorage.read(key, default.toString())
не не не, тут надо иначе

берем дефолтный объект
его сериализуем
и получаем из стринг стораджа по ключу значение и дефолтный объект как стрингу передаем внутрь

и тогда трай кетч точно не нужен

2023-03-18 04:42 UTC, JohnnySC requested changes

2023-03-18 04:42 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +    fun save(key: String, src: Any)
еще дай норм имя аргументу: ты сейвим объект, а не соурс

2023-03-18 05:47 UTC, JohnnySC requested changes

2023-03-18 05:47 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +        override fun <T> read(key: String, default: Any, clazz: Class<T>): T {
на самом деле тут 2 улучшения можно сделать
1. не Any а Т который наследник Т
2. класс не нужен, у тебя уже есть объект дефолт

2023-03-18 06:35 UTC, JohnnySC approved these changes

2023-03-18 06:37 UTC, ekzakh commented on core/src/main/java/ru/easycode/words504/data/ObjectStorage.kt
> +        override fun <T> read(key: String, default: Any, clazz: Class<T>): T {
поправлено

2023-03-18 07:25 UTC, TroyanRoman approved these changes

2023-03-18 07:25 UTC, merged