Tts 0003 media level
berhram/Words504 pull request #34
Opened 2023-03-18 09:05 UTC by Pakollya

2023-03-18 09:18 UTC, JohnnySC requested changes

2023-03-18 09:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/MediaLevel.kt
> +    fun isLowLevel(lowLevelPercentage: Int = 30): Boolean
я не хочу передавать никакие аргументы в метод чтоб узнать тихо или нет. определи сам в классе

2023-03-18 09:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/MediaLevel.kt
> +    fun currentLevel(): Int
зачем кому либо знать текущий уровень и максимальный? достаточно 1 метода

2023-03-18 09:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/ProvideSystemService.kt
> +    fun <T: Any> provideService(context: Context): T
передавать контекст надо в конструктор класса,  а не в метод

2023-03-18 09:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/ProvideSystemService.kt
> +    abstract class Abstract<K: Any>(
зачем дженерик на абстракт класс если он не нужен и у тебя метода дженерик

2023-03-18 09:18 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/ProvideSystemService.kt
> +    class AudioManager : Abstract<AudioManager>(Context.AUDIO_SERVICE)
зачем нам в принципе этот файл?

2023-03-18 19:18 UTC, Pakollya commented on core/src/main/java/ru/easycode/words504/tts/ProvideSystemService.kt
> +    class AudioManager : Abstract<AudioManager>(Context.AUDIO_SERVICE)
Для сервис локатора 
Была задумка таким образом провайдить зависимость

2023-03-19 05:34 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/ProvideSystemService.kt
> +    class AudioManager : Abstract<AudioManager>(Context.AUDIO_SERVICE)
я не вижу смысла в этом файле : перемести все в базовый класс МедиаЛевела

2023-03-19 05:35 UTC, JohnnySC requested changes
убери лишний класс и напиши все в одном

2023-03-19 08:48 UTC, JohnnySC requested changes

2023-03-19 08:48 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/MediaLevel.kt
> +        override fun isLowLevel() = 30 >= 100 * manager.getStreamVolume(streamType) /
вынеси 30 в константу и назови как threshold

2023-03-19 08:51 UTC, JohnnySC requested changes

2023-03-19 08:51 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/MediaLevel.kt
> +            context.applicationContext.getSystemService(Context.AUDIO_SERVICE) as AudioManager
ты и так передашь контекст апликейшна. не надо еще раз брать апликейшнконтекст

2023-03-19 11:05 UTC, JohnnySC approved these changes

2023-03-19 14:41 UTC, JohnnySC commented
@Pakollya удовлетвори линтер

2023-03-19 17:33 UTC, berhram approved these changes

2023-03-19 17:34 UTC, berhram approved these changes

2023-03-19 17:34 UTC, merged