FIX-0001 SomeViewModelTest
berhram/Words504 pull request #37
Opened 2023-03-18 11:48 UTC by szareckii

2023-03-18 12:30 UTC, JohnnySC requested changes

2023-03-18 12:30 UTC, JohnnySC commented on app/build.gradle
> +    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$rootProject.kotlinxCoroutinesTest"
итого 2 зависимости?

2023-03-18 12:30 UTC, JohnnySC commented on core/build.gradle
> +    api "org.jetbrains.kotlinx:kotlinx-coroutines-test:$rootProject.kotlinxCoroutinesTest"
а нет тестАпи?

2023-03-18 12:30 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/SomeViewModelTest.kt
> +    ) : BaseViewModel(dispatchers) {
какой смысл наследоваться от базовой вмки если функцию внутри нее не юзаешь?

2023-03-19 13:09 UTC, szareckii commented on app/build.gradle
> +    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$rootProject.kotlinxCoroutinesTest"
удалил, т.к. в app не используется

2023-03-19 13:10 UTC, szareckii commented on core/build.gradle
> +    api "org.jetbrains.kotlinx:kotlinx-coroutines-test:$rootProject.kotlinxCoroutinesTest"
тестАпи нет судя по https://developer.android.com/studio/build/dependencies?utm_source=android-studio#dependency_configurations

2023-03-19 13:11 UTC, szareckii commented on core/src/test/java/ru/easycode/words504/SomeViewModelTest.kt
> +    ) : BaseViewModel(dispatchers) {
поправил

2023-03-19 13:39 UTC, berhram requested changes

2023-03-19 13:39 UTC, berhram commented on core/build.gradle
> +    api "junit:junit:$rootProject.junitTest"
redundant, нигде не используется, есть  тестимлпементация уже в в апп модуле

2023-03-19 14:11 UTC, berhram approved these changes

2023-03-19 14:13 UTC, merged