CORE-0014 Added Storage and storage unit test
berhram/Words504 pull request #39
Opened 2023-03-18 15:56 UTC by VnukovNS

сделано по условиям таски - интерфейс, который наследуется от симпл и обджект стореджа, класс, который принимает в себя 2 зависимости и проксирует их в функции этих зависимостей. В юнитах сделал фейки с простыми примерами - стринга для симпл и отдельный фейк класс для обджекта

2023-03-19 17:27 UTC, berhram requested changes

2023-03-19 17:27 UTC, berhram commented on core/src/test/java/ru/easycode/words504/data/StorageTest.kt
> +    private class FakeObjectStorage : ObjectStorage {
это нужно в бейз тест

2023-03-19 17:27 UTC, berhram commented on core/src/test/java/ru/easycode/words504/data/StorageTest.kt
> +    private class FakeSimpleStorage : SimpleStorage {
это нужно в бейз тест

2023-03-19 17:27 UTC, berhram commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +    protected class TestMap() {
не нужно, ты внутри мокового в бейзе сделай пустую мапу (зачем вообще пренаселять её этим "" to "", так логику тестов можешь поломать

2023-03-19 17:29 UTC, berhram commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +    protected class TestHashMap() {
не нужно

2023-03-19 17:40 UTC, VnukovNS commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +    protected class TestMap() {
кинул в фейки пустышки

2023-03-19 17:40 UTC, berhram commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +        private var hashMap = hashMapOf<String, String>()
зачем именно хэшмапа?

2023-03-19 17:41 UTC, VnukovNS commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +        private var hashMap = hashMapOf<String, String>()
Оганнес попросил)) @JohnnySC

2023-03-19 17:58 UTC, berhram requested changes

2023-03-19 17:58 UTC, berhram commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +        private var map = mutableMapOf<Any, Any>()
could be val

2023-03-19 17:58 UTC, berhram commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +        private var map = mutableMapOf<String, String>()
could be val

2023-03-19 17:58 UTC, berhram commented on core/src/test/java/ru/easycode/words504/data/StorageTest.kt
> +    fun `test read from SimpleStorage empty`() {
проблемы с неймингом: и так понятно что это тест. во вторых мы тестируем класс Storage, а не Simple или Object сторадж, поэтому его методы мы и проверяем. Например "read string when storage is empty"

2023-03-19 18:01 UTC, berhram requested changes

2023-03-19 18:01 UTC, berhram commented on core/src/test/java/ru/easycode/words504/data/StorageTest.kt
> +    fun `test save and read from SimpleStorage`() {
тестируй в 1 методе 1 метод из тестируемого объекта

2023-03-19 18:11 UTC, VnukovNS commented on core/src/test/java/ru/easycode/words504/data/StorageTest.kt
> +    fun `test save and read from SimpleStorage`() {
так тут получается просто проверка на то, сохранили ли мы или нет - в начале сохраняем, потом читаем сохраненное значение

2023-03-19 19:43 UTC, berhram approved these changes

2023-03-20 02:15 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/data/StorageTest.kt
> +    fun `test save and read from SimpleStorage`() {
@berhram чтобы прочитать сначала надо сохранить

2023-03-20 02:16 UTC, JohnnySC requested changes

2023-03-20 02:16 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/BaseTest.kt
> +        private val map = mutableMapOf<Any, Any>()
почему ени ени если ключ стринга всегда?

2023-03-20 11:01 UTC, merged