Origin/feature/cloud 0006 handle error
berhram/Words504 pull request #42
Opened 2023-03-19 15:37 UTC by TroyanRoman

Сделал интерфейс обработки ошибок в коре. Преобразовывает любые ошибки в доменные. В доменный уровень добавлены наследники, -  обработчик сетевых ошибок и обработчик ошибочных ответов от сервера
Так же добавлены классы ошибок доменного уровня(какие нашел в документации дипла).  И немного юнит-тестов. Хотя не уверен, что для этих классов в таком именно виде они нужны.

2023-03-19 17:37 UTC, Dmitry-boroda approved these changes

2023-03-20 02:21 UTC, JohnnySC requested changes

2023-03-20 02:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/data/HandleError.kt
> +interface HandleError<S : Any, E : DomainError> {
хендл эррора будет работать не только с домейн еррором но и презентейшном. убери у второго дженерика домейнеррор ограчинение и сделай эни

2023-03-20 02:21 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/domain/HandleDomainError.kt
> +            is UnknownHostException -> NoInternetConnectionError()
исследуй ситуацию с "нет интернета" бывает что и java.net.ConnnectException

2023-03-20 02:21 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/core/domain/HandleDomainErrorTest.kt
> +        assertEquals(expectedDomainError.javaClass, actual.javaClass)
асерть объекты целиком

2023-03-20 02:21 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/core/domain/HandleDomainErrorTest.kt
> +    private class FakeHandleHttp : HandleError<Response<*>, DomainError> {
фейк должен быть проще. в 1 линию

2023-03-20 12:09 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/domain/DomainError.kt
> +interface DomainError
надо чтоб он был наследником Throwable

2023-03-21 04:42 UTC, JohnnySC approved these changes

2023-03-21 04:43 UTC, merged