LanguagesCloud and LanguagesService (API)
berhram/Words504 pull request #44
Opened 2023-03-20 13:17 UTC by lancerita

2023-03-20 19:19 UTC, lancerita commented
Исправила перепутанные запрос и ответ от сервера. Добавила проверку языка. Но пока без теста самой апи

2023-03-20 19:34 UTC, yuriysurzhikov requested changes

2023-03-20 19:34 UTC, yuriysurzhikov commented on core/src/main/java/ru/easycode/words504/data/LanguagesCloud.kt
> +            return language == "English"
1. Здесь language - это код языка, для английского это "en".
2. Если ты наследуешься от LanguagesCloud(кстати переименуй на LanguageCloud), то объяви метод в интерфейсе, а тут сделай override

2023-03-20 19:34 UTC, yuriysurzhikov commented on core/src/main/java/ru/easycode/words504/data/LanguagesService.kt
>      @GET("languages?type=target HTTP/2")
Удали все что идет после "languages", потому что у тебя Query уже объявлен в параметре метода, как и должно быть. "target" будет передаваться в качестве параметра.

2023-03-20 19:34 UTC, yuriysurzhikov commented on core/src/main/java/ru/easycode/words504/data/LanguagesCloud.kt
> +        private val supports_formality: Boolean,
Сделай нормальный нейминг, никаких underscore быть не должно.

2023-03-21 13:40 UTC, berhram approved these changes

2023-03-22 05:14 UTC, JohnnySC requested changes

2023-03-22 05:14 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/language/LanguageCloud.kt
> +            return languageCode.lowercase().startsWith("en")
а проверили документацию? какие там варианты с инглишем? только стартует или содержит?

2023-03-22 05:14 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/data/language/LanguagesService.kt
> +    suspend fun getLanguages(@Query("type") type: String): Response<List<LanguageCloud>>
зачем нам респонс?

2023-03-23 03:16 UTC, yuriysurzhikov commented
@lancerita я же кидал тебе патч, посмотри сообщение в ТГ, там описано что сделать нужно

2023-03-23 05:24 UTC, JohnnySC approved these changes

2023-03-23 05:46 UTC, yuriysurzhikov approved these changes

2023-03-23 05:48 UTC, merged