DICT-0003 ChosenLanguage
berhram/Words504 pull request #47
Opened 2023-03-21 11:32 UTC by Nilsolk

2023-03-21 11:52 UTC, JohnnySC requested changes

2023-03-21 11:52 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/ChosenLanguage.kt
> +interface ChosenLanguage : ObjectStorage {
совсем не то что ожидалось

тебе надо сделать отдельно 3 интерфейса

сохранить
прочитать
и мутабельный

также модель языка с кодом и именем как в апи от дипла

2023-03-21 15:22 UTC, JohnnySC requested changes

2023-03-21 15:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/Empty.kt
> +interface Empty : SaveOrReadLanguage {
емпти в ядре не должен ниоткого наследоваться

2023-03-21 15:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/LanguageCache.kt
> +    class Base(private val key: String, private val name: String) : Empty {
если пишем интерфейс А то внутри смарт контрактом класс Бейз будет наследовать А .
исправь

2023-03-21 15:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/SaveOrReadLanguage.kt
> +interface SaveOrReadLanguage {
interface ChosenLanguageCache

2023-03-21 15:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/SaveOrReadLanguage.kt
> +        fun <T : Any> read(default: T): T
не надо дженериков. мы четко понимаем что будем отдавать : LanguageCache

2023-03-21 15:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/SaveOrReadLanguage.kt
> +        fun save(obj: Any)
и сейвим мы конкретно LanguageCache

2023-03-21 15:22 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/SaveOrReadLanguage.kt
> +    class Base(private val objectStorage: ObjectStorage) : Mutable {
когда закончишь покрой этот класс юнит тестом

2023-03-21 21:13 UTC, Nilsolk commented
Не понимаю почмеу не проходят юнит тесты, после того, как сделал и запушил, все норм было, но линт ругался, потом престали проходить

2023-03-22 04:36 UTC, JohnnySC requested changes

2023-03-22 04:36 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/ChosenLanguageCache.kt
> +        fun read(default: LanguageCache): LanguageCache
не надо снаружи принимать дефолт. он будет внутри метода в классе

2023-03-22 05:41 UTC, JohnnySC requested changes

2023-03-22 05:41 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/ChosenLanguageCache.kt
> +        fun read(): LanguageCache
а теперь влей в себя новый мейн и наследуйся от дженерик сейв и рид

2023-03-22 06:14 UTC, JohnnySC requested changes

2023-03-22 06:14 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/ChosenLanguageCacheTest.kt
> +        private const val KEY = "ChosenLanguageKey"
чтоб не дублировать ключ прими его в конструктор класса

2023-03-22 06:14 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/core/ChosenLanguageCache.kt
> +            private const val LANGUAGE_KEY = "ChosenLanguageKey"
перемести ключ в конструктор последним аргументом с дефолт значением

2023-03-22 06:43 UTC, Nilsolk commented on core/src/test/java/ru/easycode/words504/ChosenLanguageCacheTest.kt
> +        private const val KEY = "ChosenLanguageKey"
Немного не понял как не дублировать, ведь я ключ использую в обжект сторадже, а в сам конструктор теста я предать не могу

2023-03-22 07:18 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/ChosenLanguageCacheTest.kt
> +        private const val KEY = "ChosenLanguageKey"
посмотри второй комментарий. речь про ChosenLanguageCache

2023-03-22 07:31 UTC, JohnnySC approved these changes

2023-03-23 04:16 UTC, JohnnySC requested changes

2023-03-23 04:16 UTC, JohnnySC commented on core/src/test/java/ru/easycode/words504/ChosenLanguageCacheTest.kt
> +    fun empty_data() {
названия тестовых функций пишем в кривых одинарных кавыхчках с пробелами `

2023-03-23 05:55 UTC, JohnnySC approved these changes

2023-03-23 06:02 UTC, yuriysurzhikov approved these changes

2023-03-23 06:07 UTC, merged