tts-0002 Communication
berhram/Words504 pull request #48
Opened 2023-03-21 17:16 UTC by eels911

2023-03-21 17:50 UTC, eels911 commented on core/src/main/java/ru/easycode/words504/tts/TTSCommunication.kt
> +    class Base : Communication.Abstract<List<String>>(), Update
оставить только класс base?

2023-03-21 18:28 UTC, Pakollya commented on core/src/main/java/ru/easycode/words504/tts/TTSCommunication.kt
> +    class Base : Communication.Abstract<List<String>>(), Update
оставить только Base : Communication.Abstract не кажется тем что нам нужно
скорее всего лучше все-таки разнести на несколько интерфейсов
Update : Communication.Update
Observe : Communication.Observe
Mutable : Update, Observe
Base : Mutable
Я бы так сделал

2023-03-21 18:38 UTC, eels911 commented on core/src/main/java/ru/easycode/words504/tts/TTSCommunication.kt
> +    class Base : Communication.Abstract<List<String>>(), Update
Base : Mutable , то как переопределить map()? я так поняла пока неизвестен точно source и в какой тип мапить

2023-03-22 05:12 UTC, JohnnySC requested changes

2023-03-22 05:12 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/tts/TTSCommunication.kt
> +    class Base : Communication.Abstract<List<String>>()
интерфейс сегрегейшн нужен для того чтоб читали в 1 месте и отправляли из разных

2023-03-22 11:58 UTC, JohnnySC approved these changes

2023-03-22 12:07 UTC, banancheg23 approved these changes

2023-03-22 12:08 UTC, merged