Admt 0002 custom input layout
berhram/Words504 pull request #49
Opened 2023-03-21 18:13 UTC by TroyanRoman

Сделал кастомного наследника TextInputLayout и интерфейс для отображения нужных данны в хелпере

2023-03-22 05:11 UTC, JohnnySC requested changes

2023-03-22 05:11 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/presentation/CustomInputLayout.kt
> +class CustomInputLayout : TextInputLayout, ShowText {
таска о том чтоб в ней было заинкуапсулирована вся логика: а не прилетало снаружи

2023-03-29 22:03 UTC, TroyanRoman commented
Пока получился вот такой вариант. Из текствотчера получаем текущее состояние строки, сравниваем с предыдущим, смотрим , есть ли разделители для слова, если прошли разделитель - добавляем к предыдущему варианту строки хэлпера индекс следующего слова. при удалении - удаляем.

2023-03-30 01:55 UTC, JohnnySC requested changes
Как много кода и нисколько юнит тестов

2023-03-30 01:55 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/presentation/CustomInputLayout.kt
> +    override fun show() {
почему не в инит блоке?

2023-04-02 07:22 UTC, closed without merging