Admt 0002 custom input layout
berhram/Words504 pull request #61
Opened 2023-04-02 07:41 UTC by TroyanRoman

2023-04-03 02:50 UTC, JohnnySC requested changes

2023-04-03 02:50 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/presentation/CustomInputLayout.kt
> +        val inputEditText: TextInputEditText = findViewById(R.id.myEditText)
почему бы не брать поле ввода через getEditText. так ты обязуешь поле ввода иметь айди причем непонятный. убери этот айди

2023-04-03 03:19 UTC, JohnnySC requested changes

2023-04-03 03:19 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/presentation/custom/CustomEditTextWatcher.kt
> +class CustomEditTextWatcher(private val editTextLayout: TextInputLayout) : EditTextWatcher() {
вместо инпутлейаута пусть будет мапер юнит стринг

2023-04-03 03:19 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/presentation/custom/CustomEditTextWatcher.kt
> +        val indexes = HandleIndexes(LetterMatch(), DelimiterMatch())
вынеси создание в поле класса

2023-04-03 03:19 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/presentation/custom/HandleIndexes.kt
> +            val previousSymbol = if (index > 0) source[index - 1] else ' '
пробел в константы

2023-04-03 03:19 UTC, JohnnySC commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/myEditText"
убери айди вообще

2023-04-04 04:49 UTC, JohnnySC requested changes

2023-04-04 04:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/WordsIndexesInputLayout.kt
> +    override fun onFinishInflate() {
убери этот метод и сделай просто инит который дергаешь в конструкторах

2023-04-04 04:49 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/input/HelperIndexes.kt
> +class HelperIndexes(private val helper: (output: CharSequence) -> Unit) : Mapper.Unit<String> {
какой толк от этого класса? удали

2023-04-04 04:52 UTC, JohnnySC requested changes

2023-04-04 04:52 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/WordsIndexesInputLayout.kt
> +class WordsIndexesInputLayout : TextInputLayout {
просто тут имплементани Мапер.юнит стринг и все

2023-04-06 05:43 UTC, JohnnySC requested changes

2023-04-06 05:43 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/WordsIndexesInputLayout.kt
> +    override fun init(attrs: AttributeSet) {
что тут происходит? какие ты берешь атрибуты и почему в 2 конструкторах из 3? убери это все

2023-04-07 00:54 UTC, JohnnySC requested changes

2023-04-07 00:54 UTC, JohnnySC commented on app/src/main/res/layout/words_indexes_input_layout.xml
> +        android:layout_height="match_parent" />
может все же высоту wrap_content?

2023-04-07 00:54 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/WordsIndexesInputLayout.kt
> +        (context.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater)
юзай простой метод LayoutInflater.from(context)

2023-04-07 04:00 UTC, JohnnySC approved these changes

2023-04-07 11:33 UTC, berhram approved these changes

2023-04-07 11:33 UTC, merged