DICT-0006 LanguagesRepository
berhram/Words504 pull request #63
Opened 2023-04-05 17:37 UTC by ekzakh

Languages repository and tests

2023-04-06 05:40 UTC, JohnnySC requested changes

2023-04-06 05:40 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/data/cache/LanguageCache.kt
> +    fun key(): String
зачем это если уже есть мапер?

2023-04-06 05:40 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/domain/LanguagesRepository.kt
> +    interface Languages {
надо объединить получение всех языков и сохранение конкретного потому что оно будет провайдиться как 1 интерфейс

2023-04-06 05:40 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeCacheDataSource.kt
> +class FakeCacheDataSource : LanguagesCacheDataSource.Mutable {
зачем это?

2023-04-06 05:40 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeCacheMapper.kt
> +class FakeCacheMapper : LanguageCloud.Mapper<LanguageCache> {
зачем фейк класс?

2023-04-06 05:40 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeChosenLanguageCache.kt
> +class FakeChosenLanguageCache : ChosenLanguageCache.Mutable {
почему фейк если у нас уже есть настоящий класс?

2023-04-06 05:40 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeLanguagesCloudDataSource.kt
> +class FakeLanguagesCloudDataSource : LanguagesCloudDataSource {
зачем нам фейк если можно написать тру? но сначала надо абстрактный написать

2023-04-06 05:40 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/data/repository/LanguageRepositoryTest.kt
> +    private lateinit var chosenLanguageCache: FakeChosenLanguageCache
если все фейки ради юнит тестов то их место здесь с модификатором приват

2023-04-06 07:34 UTC, ekzakh commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeCacheDataSource.kt
> +class FakeCacheDataSource : LanguagesCacheDataSource.Mutable {
На одном из предыдущих ПР было замечание по поводу использования тру классов в тестах,  не завязываться на реальные реализации

2023-04-06 07:35 UTC, ekzakh commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeCacheMapper.kt
> +class FakeCacheMapper : LanguageCloud.Mapper<LanguageCache> {
Заменила на тру, т.к. он элементарный

2023-04-06 07:36 UTC, ekzakh commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeChosenLanguageCache.kt
> +class FakeChosenLanguageCache : ChosenLanguageCache.Mutable {
выше ответила

2023-04-07 00:48 UTC, JohnnySC approved these changes

2023-04-07 00:48 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/languages/data/cache/LanguageKeyMapper.kt
> +    class SameLanguage(private val otherKey: String) : LanguageKeyMapper {
я имел ввиду положить этот класс внутрь интерфейса мапера который исходный т.е. LanguageCache.Mapper. но да ладно. и так пойдет

2023-04-07 00:48 UTC, JohnnySC commented on app/src/test/java/ru/easycode/words504/languages/data/repository/FakeCacheDataSource.kt
> +class FakeCacheDataSource : LanguagesCacheDataSource.Mutable {
все фейк классы должны быть приватными и лежать в тестовом пакете

2023-04-07 11:28 UTC, berhram approved these changes

2023-04-07 11:28 UTC, merged