CORE-0022 implemented ProvideViewModel & BaseFragment created
berhram/Words504 pull request #68
Opened 2023-04-08 19:33 UTC by TroyanRoman

2023-04-08 19:40 UTC, TroyanRoman commented
в имплементации ProvideViewModel в App пока дефолтная фабрика вьюмоделей,  до тех пор, пока не написали свою

2023-04-09 03:09 UTC, JohnnySC requested changes

2023-04-09 03:09 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/App.kt
> +        ViewModelProvider(owner)[clazz]
здесь туду оставь TODO()

2023-04-09 03:09 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/presentation/BaseFragment.kt
> +    protected abstract val layoutResId: Int
мы будем юзать вьюбиндинг. удали пока это и криейтвью

2023-04-09 08:11 UTC, JohnnySC approved these changes

2023-04-09 08:18 UTC, yuriysurzhikov approved these changes

2023-04-09 08:40 UTC, merged