add retrofit and gson dependencies
berhram/Words504 pull request #7
Opened 2023-03-14 15:10 UTC by eels911

2023-03-14 15:19 UTC, Dima-Variukhin commented on app/build.gradle
> +    implementation "com.squareup.retrofit2:converter-gson:$rootProject.gsonVersion"
@berhram @TomNotArtem Будем ли следовать кодстайлу, где оставляем пустую линию, в конце каждого файла? Git, вон красненьким подсвечивает)

2023-03-14 15:27 UTC, berhram commented on app/build.gradle
> +    implementation "com.squareup.retrofit2:converter-gson:$rootProject.gsonVersion"
на проекте не думаю что скажется как-то, пусть подсвечивает)

2023-03-14 15:27 UTC, berhram approved these changes

2023-03-14 15:38 UTC, Dima-Variukhin approved these changes

2023-03-14 15:44 UTC, berhram commented
Измени пж название у ПР-а и коммита как у остальных

2023-03-14 15:44 UTC, berhram requested changes
Измени коммит и имя пр до соответсвия остальным (добавить номер таски)

2023-03-15 06:26 UTC, JohnnySC approved these changes

2023-03-15 06:27 UTC, berhram approved these changes

2023-03-15 06:27 UTC, merged