TTS-0001 core tts
berhram/Words504 pull request #76
Opened 2023-04-10 06:13 UTC by banancheg23

Добавил интерфейс и базовую реализацию TTSEngine и активити для теста ТТС. В активити 3 кнопки. Одна произносит текст одним блоком текста, вторая останавливает ТТС, третья разбивает текст по предложениям и читает по очереди. Через колбэки указываю какой блок читается в данный момент и какой закончил читаться

2023-06-29 03:26 UTC, berhram approved these changes

2023-06-30 09:29 UTC, JohnnySC requested changes

2023-06-30 09:29 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/tts/data/TTSEngine.kt
> +                override fun onError(utteranceId: String) = Unit
а ошибки надо хендлить же. оставь туду

2023-06-30 09:29 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/tts/data/TTSEngine.kt
> +            if (!isPaused) {
if (isPaused)
else

2023-06-30 09:29 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/tts/data/TTSControl.kt
> +    fun changePlayback()
что это значит? что происходит?

2023-06-30 09:29 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/tts/presentation/TTSTestActivity.kt
> +        viewModel.init {}
это что за инит такой?

2023-06-30 09:54 UTC, berhram commented on app/src/main/java/ru/easycode/words504/tts/data/TTSEngine.kt
> +                override fun onError(utteranceId: String) = Unit
другой метод onError их хендлит, не депрекейтед который

2023-06-30 10:00 UTC, berhram commented on app/src/main/java/ru/easycode/words504/tts/presentation/TTSTestActivity.kt
> +        viewModel.init {}
там листенер инита для ттс андроидовского, по идее если мы всё настроили что нужно -- указали в манифесте и тд, то у нас инит не может фейлануться

2023-06-30 10:00 UTC, berhram commented on app/src/main/java/ru/easycode/words504/tts/data/TTSControl.kt
> +    fun changePlayback()
done, renamed

2023-06-30 10:21 UTC, JohnnySC requested changes

2023-06-30 10:21 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/tts/presentation/TTSTestActivity.kt
> +        viewModel.init {}
я о том что лямбда пустая. или хендлить надо или убрать это

2023-06-30 11:51 UTC, JohnnySC approved these changes

2023-06-30 20:54 UTC, merged