fix/TRNS-0003_fix_Translate_Service
berhram/Words504 pull request #82
Opened 2023-04-13 14:18 UTC by eels911

2023-04-13 22:22 UTC, berhram approved these changes

2023-04-13 22:23 UTC, berhram requested changes
оформи пр - имя по образцу, если таски нет создай в канбане с префиксом FIX (такие же были поэтому номер не напутай)

2023-04-14 15:16 UTC, berhram approved these changes

2023-04-15 14:38 UTC, blastka approved these changes

2023-04-15 15:01 UTC, JohnnySC approved these changes

2023-04-15 15:01 UTC, merged