ADMT-0007 admin tools dependency
berhram/Words504 pull request #89
Opened 2023-04-16 13:28 UTC by ekzakh

Зависимости для админки

2023-04-16 13:46 UTC, JohnnySC requested changes

2023-04-16 13:46 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/sl/AdminModule.kt
> +    private val navigationCommunication: NavigationCommunication.Mutable
пусть сюда придет кормодуль

2023-04-16 13:46 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/sl/CoreModule.kt
> +        override fun provideAdminScope() = AdminScopeModule.Base()
суть скоуп модуля чтоб он был 1. сделай полем

2023-04-16 14:01 UTC, JohnnySC requested changes

2023-04-16 14:01 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/sl/AdminModule.kt
> +    private val navigationCommunication: NavigationCommunication.Mutable
убери навигацию. оставь только кор модуль

2023-04-17 04:28 UTC, JohnnySC requested changes

2023-04-17 04:28 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/App.kt
> +    private lateinit var viewModelsAdminFactory: ViewModelsFactory
не надо было создавать отдельную фабрику вмок

2023-04-17 04:28 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/App.kt
> +    override fun <T : ViewModel> adminViewModel(clazz: Class<T>, owner: ViewModelStoreOwner): T =
убери это

2023-04-17 04:28 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/App.kt
> +            BaseDependencyContainer(coreModule)
у тебя цепочка обязанностей, просто добавь админдепенденсиконтейнер в базовый

2023-04-17 04:28 UTC, JohnnySC commented on core/src/main/java/ru/easycode/words504/sl/ProvideAdminViewModel.kt
> +interface ProvideAdminViewModel {
удали это

2023-04-17 06:12 UTC, JohnnySC requested changes

2023-04-17 06:12 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/App.kt
> +    private lateinit var coreModule: CoreModule
верни теперь кормодуль на место

2023-04-17 06:33 UTC, JohnnySC approved these changes

2023-04-17 06:33 UTC, berhram approved these changes

2023-04-17 06:34 UTC, merged