ADMT-0005 added Admintools activity
berhram/Words504 pull request #96
Opened 2023-04-18 05:38 UTC by 00hadron

Добавлена активити для AdminTools. 
Сделан переход по кнопке из MainActivity.

2023-04-18 05:57 UTC, JohnnySC requested changes

2023-04-18 05:57 UTC, JohnnySC commented on app/src/main/res/layout/activity_admin.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
зачем обертка линеарлейаут? убери ее

2023-04-18 06:39 UTC, JohnnySC requested changes

2023-04-18 06:39 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminActivity.kt
> +        setContentView(R.layout.activity_admin)
обсервь навигацию из вмки

2023-04-19 00:14 UTC, 00hadron commented
- Исправлена разметка в Мейн и Админ активити
- Добавлен обсервер в Админ активити

2023-04-19 04:34 UTC, JohnnySC requested changes

2023-04-19 04:34 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/MainActivity.kt
> +    private lateinit var gotoAdminButton: Button
зачем выносить в поле если оно кроме онкриейта нигде не нужно?

2023-04-19 04:34 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminActivity.kt
> +        viewModel.observe(this) {}
молодец. обсервишь, а код внутри напишешь?

2023-04-19 04:34 UTC, JohnnySC commented on app/src/main/res/layout/activity_admin.xml
> +    tools:context=".admintools.presentation.AdminActivity">
закрывай тег хмл сразу />

2023-04-19 04:34 UTC, JohnnySC commented on app/src/main/res/layout/activity_admin.xml
> +    android:orientation="vertical"
у фрейма нет ориентации

2023-04-19 04:34 UTC, JohnnySC commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content" />
высоту матчпарент

2023-04-19 09:42 UTC, 00hadron commented
Исправлен observe
Исправлена разметка
Переопределен onBackPressed()

2023-04-19 09:55 UTC, JohnnySC requested changes

2023-04-19 09:55 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminActivity.kt
> +    override fun onBackPressed() { }
onBackPressed() = Unit

2023-04-19 09:55 UTC, JohnnySC commented on app/src/main/java/ru/easycode/words504/admintools/presentation/AdminActivity.kt
> +        viewModel.observe(this) { ui ->
ui? убери

2023-04-19 10:48 UTC, JohnnySC approved these changes

2023-04-19 10:49 UTC, ekzakh approved these changes

2023-04-19 10:49 UTC, merged